name: Check URLs

on:
  push:
    branches: [ '2709-validation-jekyll' ]
#  schedule:
#    - cron: '0 0 * * 6' # Every Saturday at 00:00.

jobs:
  check_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Check links
        run: bundle exec jekyll build
        env:
          MUST_CHECK_URLS: true
